// Key bindings for the DevTerm keyboard (make KEYBOARD=devterm).
// The uConsole bindings are in layers.h, the syntax is the same.
//
// Keys that exist on both keyboards are bound like on the uConsole.
// Keys that only the DevTerm has follow the stock DevTerm firmware.

// default layer
LAYER(1, "Main");

TRACKBALL_SPEED(100);
TRACKBALL_ACCELERATION(0.2f);
TRACKBALL_SCROLL_VERTICAL_SPEED(100);
TRACKBALL_SCROLL_VERTICAL_ACCELERATION(0.5f);
TRACKBALL_SCROLL_HORIZONTAL_SPEED(100);
TRACKBALL_SCROLL_HORIZONTAL_ACCELERATION(0.3f);

BIND(BUTTON_SELECT, KEY_KEYPAD_MINUS);
BIND(BUTTON_START, KEY_KEYPAD_PLUS);
BIND(BUTTON_VOLUME, CONSUMER_VOLUME_DOWN);
BIND(BUTTON_GRAVE, KEY_GRAVE);
BIND(BUTTON_BRACE_LEFT, KEY_BRACE_LEFT);
BIND(BUTTON_BRACE_RIGHT, KEY_BRACE_RIGHT);
BIND(BUTTON_MINUS, KEY_MINUS);
BIND(BUTTON_EQUAL, KEY_EQUAL);
BIND(BUTTON_1, KEY_1);
BIND(BUTTON_2, KEY_2);
BIND(BUTTON_3, KEY_3);
BIND(BUTTON_4, KEY_4);
BIND(BUTTON_5, KEY_5);
BIND(BUTTON_6, KEY_6);
BIND(BUTTON_7, KEY_7);
BIND(BUTTON_8, KEY_8);
BIND(BUTTON_9, KEY_9);
BIND(BUTTON_0, KEY_0);
BIND(BUTTON_ESC, KEY_ESC);
BIND(BUTTON_TAB, KEY_TAB);
BIND(BUTTON_Q, KEY_Q);
BIND(BUTTON_W, KEY_W);
BIND(BUTTON_E, KEY_E);
BIND(BUTTON_R, KEY_R);
BIND(BUTTON_T, KEY_T);
BIND(BUTTON_Y, KEY_Y);
BIND(BUTTON_U, KEY_U);
BIND(BUTTON_I, KEY_I);
BIND(BUTTON_O, KEY_O);
BIND(BUTTON_P, KEY_P);
BIND(BUTTON_A, KEY_A);
BIND(BUTTON_S, KEY_S);
BIND(BUTTON_D, KEY_D);
BIND(BUTTON_F, KEY_F);
BIND(BUTTON_G, KEY_G);
BIND(BUTTON_H, KEY_H);
BIND(BUTTON_J, KEY_J);
BIND(BUTTON_K, KEY_K);
BIND(BUTTON_L, KEY_L);
BIND(BUTTON_Z, KEY_Z);
BIND(BUTTON_X, KEY_X);
BIND(BUTTON_C, KEY_C);
BIND(BUTTON_V, KEY_V);
BIND(BUTTON_B, KEY_B);
BIND(BUTTON_N, KEY_N);
BIND(BUTTON_M, KEY_M);
BIND(BUTTON_COMMA, KEY_COMMA);
BIND(BUTTON_DOT, KEY_DOT);
BIND(BUTTON_SLASH, KEY_SLASH);
BIND(BUTTON_BACKSLASH, KEY_BACKSLASH);
BIND(BUTTON_SEMICOLON, KEY_SEMICOLON);
BIND(BUTTON_APOSTROPHE, KEY_APOSTROPHE);
BIND(BUTTON_BACKSPACE, KEY_BACKSPACE);
BIND(BUTTON_ENTER, KEY_ENTER);
BIND(BUTTON_FN, SK_FN_KEY);
BIND(BUTTON_SPACE, KEY_SPACE);
BIND(BUTTON_TRACKBALL, MOUSE_LEFT);
BIND(BUTTON_SHIFT_LEFT, KEY_SHIFT_LEFT);
BIND(BUTTON_SHIFT_RIGHT, KEY_SHIFT_RIGHT);
BIND(BUTTON_CTRL_LEFT, KEY_CTRL_LEFT);
BIND(BUTTON_CTRL_RIGHT, KEY_CTRL_RIGHT);
BIND(BUTTON_ALT_LEFT, KEY_ALT_LEFT);
BIND(BUTTON_ALT_RIGHT, KEY_ALT_RIGHT);
BIND(BUTTON_UP, KEY_ARROW_UP);
BIND(BUTTON_DOWN, KEY_ARROW_DOWN);
BIND(BUTTON_LEFT, KEY_ARROW_LEFT);
BIND(BUTTON_RIGHT, KEY_ARROW_RIGHT);
BIND(BUTTON_GAMEPAD_UP, KEY_ARROW_UP);
BIND(BUTTON_GAMEPAD_DOWN, KEY_ARROW_DOWN);
BIND(BUTTON_GAMEPAD_LEFT, KEY_ARROW_LEFT);
BIND(BUTTON_GAMEPAD_RIGHT, KEY_ARROW_RIGHT);
BIND(BUTTON_CMD, KEY_META_RIGHT);
BIND(BUTTON_GAMEPAD_A, KEY_ENTER);
BIND(BUTTON_GAMEPAD_B, KEY_META_LEFT);
BIND(BUTTON_GAMEPAD_X, MOUSE_RIGHT);
BIND(BUTTON_GAMEPAD_Y, MOUSE_LEFT);
BIND(BUTTON_MOUSE_L, MOUSE_LEFT);
BIND(BUTTON_MOUSE_M, MOUSE_MIDDLE);
BIND(BUTTON_MOUSE_R, MOUSE_RIGHT);

BIND_FN(BUTTON_SELECT, KEY_PRNT_SCRN);
BIND_FN(BUTTON_START, KEY_PAUSE);
BIND_FN(BUTTON_VOLUME, CONSUMER_MUTE);
BIND_FN(BUTTON_MINUS, KEY_F11);
BIND_FN(BUTTON_EQUAL, KEY_F12);
BIND_FN(BUTTON_1, KEY_F1);
BIND_FN(BUTTON_2, KEY_F2);
BIND_FN(BUTTON_3, KEY_F3);
BIND_FN(BUTTON_4, KEY_F4);
BIND_FN(BUTTON_5, KEY_F5);
BIND_FN(BUTTON_6, KEY_F6);
BIND_FN(BUTTON_7, KEY_F7);
BIND_FN(BUTTON_8, KEY_F8);
BIND_FN(BUTTON_9, KEY_F9);
BIND_FN(BUTTON_0, KEY_F10);
BIND_FN(BUTTON_ESC, SK_KEYBOARD_LOCK);
BIND_FN(BUTTON_TAB, KEY_CAPS_LOCK);
BIND_FN(BUTTON_U, KEY_PAGE_UP);
BIND_FN(BUTTON_I, KEY_INSERT);
BIND_FN(BUTTON_H, KEY_HOME);
BIND_FN(BUTTON_J, KEY_END);
BIND_FN(BUTTON_K, KEY_PAGE_DOWN);
BIND_FN(BUTTON_COMMA, CONSUMER_BRIGHTNESS_DOWN);
BIND_FN(BUTTON_DOT, CONSUMER_BRIGHTNESS_UP);
BIND_FN(BUTTON_BACKSPACE, KEY_DELETE);
BIND_FN(BUTTON_UP, KEY_PAGE_UP);
BIND_FN(BUTTON_DOWN, KEY_PAGE_DOWN);
BIND_FN(BUTTON_LEFT, KEY_HOME);
BIND_FN(BUTTON_RIGHT, KEY_END);
BIND_FN(BUTTON_GAMEPAD_UP, KEY_PAGE_UP);
BIND_FN(BUTTON_GAMEPAD_DOWN, KEY_PAGE_DOWN);
BIND_FN(BUTTON_GAMEPAD_LEFT, KEY_HOME);
BIND_FN(BUTTON_GAMEPAD_RIGHT, KEY_END);
BIND_FN(BUTTON_GAMEPAD_X, MOUSE_FORWARD);
BIND_FN(BUTTON_GAMEPAD_Y, MOUSE_BACK);
BIND_FN(BUTTON_GAMEPAD_A, KEY_KEYPAD_ASTERISK);
BIND_FN(BUTTON_GAMEPAD_B, KEY_KEYPAD_SLASH);
BIND_FN(BUTTON_ALT_LEFT, KEY_APPLICATION);


// Game layer
LAYER(2, "Game");

TRACKBALL_SPEED(125);
TRACKBALL_ACCELERATION(0.0f);

BIND(BUTTON_GAMEPAD_A, KEY_KEYPAD_9);
BIND(BUTTON_GAMEPAD_B, KEY_KEYPAD_7);
BIND(BUTTON_GAMEPAD_X, KEY_KEYPAD_3);
BIND(BUTTON_GAMEPAD_Y, KEY_KEYPAD_1);


// Gamepad layer
LAYER(3, "Gamepad");

TRACKBALL_SPEED(125);
TRACKBALL_ACCELERATION(0.0f);

BIND(BUTTON_SELECT, GAMEPAD_BUTTON_5);
BIND(BUTTON_START, GAMEPAD_BUTTON_6);
BIND(BUTTON_GAMEPAD_UP, GAMEPAD_UP);
BIND(BUTTON_GAMEPAD_DOWN, GAMEPAD_DOWN);
BIND(BUTTON_GAMEPAD_LEFT, GAMEPAD_LEFT);
BIND(BUTTON_GAMEPAD_RIGHT, GAMEPAD_RIGHT);
BIND(BUTTON_GAMEPAD_A, GAMEPAD_BUTTON_1);
BIND(BUTTON_GAMEPAD_B, GAMEPAD_BUTTON_2);
BIND(BUTTON_GAMEPAD_X, GAMEPAD_BUTTON_3);
BIND(BUTTON_GAMEPAD_Y, GAMEPAD_BUTTON_4);

// Disable Fn combinations for game buttons in game layer
BIND_FN(BUTTON_SELECT, KEY_NONE);
BIND_FN(BUTTON_START, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_UP, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_DOWN, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_LEFT, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_RIGHT, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_A, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_B, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_X, KEY_NONE);
BIND_FN(BUTTON_GAMEPAD_Y, KEY_NONE);
