##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Fri Apr 03 21:37:07 CEST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
# Keyboard variant: uconsole or devterm, e.g. "make KEYBOARD=devterm"
# Without KEYBOARD the firmware is built for the connected keyboard, and for the
# uConsole if no keyboard can be identified. Flashing is refused in the latter case.
KEYBOARD_SOURCE = given
ifndef KEYBOARD
KEYBOARD := $(shell bash ./tools/check_keyboard_variant.sh --detect 2>/dev/null)
ifneq ($(KEYBOARD),)
KEYBOARD_SOURCE = detected
$(info Detected the $(KEYBOARD) keyboard, building for it. Use KEYBOARD=uconsole or KEYBOARD=devterm to choose yourself.)
else
KEYBOARD_SOURCE = default
KEYBOARD := uconsole
endif
endif

# USB_PRODUCT must be the same as VARIANT_USB_PRODUCT_STRING in Core/Inc/keyboard_variant.h,
# it is used to check that the firmware is flashed to the right keyboard
ifeq ($(KEYBOARD),uconsole)
TARGET = uconsole_keyboard
KEYBOARD_VARIANT = VARIANT_UCONSOLE
USB_PRODUCT = uConsole
else ifeq ($(KEYBOARD),devterm)
TARGET = devterm_keyboard
KEYBOARD_VARIANT = VARIANT_DEVTERM
USB_PRODUCT = DevTerm
else
$(error Unknown KEYBOARD "$(KEYBOARD)", use "uconsole" or "devterm")
endif


######################################
# building variables
######################################
# debug build?
DEBUG = 0
# optimization (-O3: max speed; avoid -Ofast unless float semantics can change)
OPT = -O3


#######################################
# paths
#######################################
# Build path, every keyboard variant has its own so that objects are never mixed
ifeq ($(KEYBOARD),uconsole)
BUILD_DIR = build
else
BUILD_DIR = build/$(KEYBOARD)
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f1xx_it.c \
Core/Src/stm32f1xx_hal_msp.c \
Core/Src/keyboard_matrix.c \
Core/Src/keyboard_non_matrix.c \
Core/Src/keymaps.c \
Core/Src/trackball.c \
Core/Src/hid_keyboard.c \
Core/Src/hid_mouse.c \
Core/Src/hid_gamepad.c \
Core/Src/hid_consumer.c \
Core/Src/hid_vendor.c \
Core/Src/ratemeter.c \
Core/Src/glider.c \
Core/Src/leds.c \
Core/Src/prec_time.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c \
Core/Src/system_stm32f1xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
USB_DEVICE/App/usb_device.c \
USB_DEVICE/App/usbd_desc.c \
USB_DEVICE/App/usbd_custom_hid_if.c \
USB_DEVICE/Target/usbd_conf.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xb.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F103xB \
-DKEYBOARD_VARIANT=$(KEYBOARD_VARIANT)


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-I. \
-ICore/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy \
-IDrivers/STM32F1xx_HAL_Driver/Inc \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Include \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# make sure that the firmware is for the connected keyboard
#######################################
.PHONY: check_keyboard
check_keyboard:
ifeq ($(KEYBOARD_SOURCE),default)
	@echo "Error: can't identify the connected keyboard (not found, already in bootloader mode or not Linux)." >&2
	@echo "Choose the firmware yourself with KEYBOARD=uconsole or KEYBOARD=devterm." >&2
	@false
else
	FORCE=$(FORCE) bash ./tools/check_keyboard_variant.sh "$(USB_PRODUCT)"
endif

#######################################
# flash the device for the first time
#######################################
first_flash: check_keyboard $(BUILD_DIR)/$(TARGET).bin
	bash ./to_bootloader_original.sh
	@if [ "$$(uname -s)" = "Linux" ]; then \
		sudo dfu-util -d 1EAF:0003 -a 2 -D $(BUILD_DIR)/$(TARGET).bin || true; \
	else \
		dfu-util -d 1EAF:0003 -a 2 -D $(BUILD_DIR)/$(TARGET).bin || true; \
	fi 

#######################################
# flash the device
#######################################
flash: check_keyboard $(BUILD_DIR)/$(TARGET).bin
	bash ./to_bootloader.sh
	@if [ "$$(uname -s)" = "Linux" ]; then \
		sudo dfu-util -d 1EAF:0003 -a 2 -D $(BUILD_DIR)/$(TARGET).bin || true; \
	else \
		dfu-util -d 1EAF:0003 -a 2 -D $(BUILD_DIR)/$(TARGET).bin || true; \
	fi
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
